services:
  muze:
    # container_name: muze # optional
    image: thearyadev0/muze:amd64-latest # You can pin your tag to a specific version by replacing "latest" with a version number
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data # the database lives here
      - ./music:/app/music # your music library
      - ./covers:/app/covers # cover art
