name: biome-format
on:
  push:
    branches:
      - main
    pull_request:

jobs:
  biome-format:
    name: biome-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install @biomejs/biome --legacy-peer-deps
      - name:
        run: npx biome format .
